metal_tab={--as much as i would love to do the commented out ones... id need to think on how to do the power/plastic systems
  "copper",
  --"stone",
  "steel",
  --"plastic",
  --"ceramic",
  "titanium",
  "brass",
  "bronze",
  "tungsten",
  --"copper-tungsten",
  "nitinol"
}
gears={
  "steel",
  "nitinol",
  "titanium",
  "brass",
  "cobalt-steel",
  "tungsten"
}
a_inters={
  --["angels-gear"]={metal="iron"},--iron gear is now the angels-gear
  ["angels-axle"]={metal="steel",icon="axle",tech="angels-components-mechanical-2"},
  ["angels-roller-chain"]={metal="aluminium",icon="roller-chain",tech="angels-components-mechanical-3"},
  ["angels-spring"]={metal="titanium",icon="spring",tech="angels-components-mechanical-4"},
  --["angels-bearing"]={metal="tungsten",icon="bearing",tech="mechanical-components-5"}, --not adding lube and steel to a casting
  ["grate-iron"]={metal="iron",tech="angels-components-construction-2"},
  ["grate-steel"]={metal="steel",tech="angels-components-construction-2"},
  ["grate-aluminium"]={metal="aluminium",tech="angels-components-construction-3"},
  ["grate-titanium"]={metal="titanium",tech="angels-components-construction-4"},
  ["grate-tungsten"]={metal="tungsten",tech="angels-components-construction-5"},
  ["angels-girder"]={metal="iron",icon="girder",tech="angels-components-construction-2"},
  ["angels-rivet"]={metal="steel",icon="rivet",tech="angels-components-construction-2"},
  ["angels-bracket"]={metal="aluminium",icon="bracket",tech="angels-components-construction-3"},
  ["angels-plating"]={metal="titanium",icon="plating",tech="angels-components-construction-4"},
  ["angels-strut"]={metal="tungsten",icon="strut",tech="angels-components-construction-5"},
  ["body-1"]={metal="iron",tech="angels-components-weapons-basic"},
  ["body-2"]={metal="steel",tech="military"},
  ["body-3"]={metal="aluminium",tech="military-2"},
  ["body-4"]={metal="titanium",tech="angels-components-weapons-advanced"},
  ["body-5"]={metal="tungsten",tech="military-3"},
  ["angels-trigger"]={metal="iron",icon="trigger",tech="angels-components-weapons-basic"},
  ["angels-explosionchamber"]={metal="steel",icon="explosion-chamber",tech="military"},
  ["angels-fluidchamber"]={metal="aluminium",icon="fluid-chamber",tech="military-2"},
  ["angels-energycrystal"]={metal="titanium",icon="energy-chamber",tech="angels-components-weapons-advanced"},
  --["angels-acceleratorcoil"]={metal="tungsten",icon="accelerator-coil",tech="military-3"},
  ["cable-shielding-1"]={metal="copper",icon="cable-shield-1",tech="angels-components-cabling-2"},
  ["cable-shielding-2"]={metal="tin",icon="cable-shield-2",tech="angels-components-cabling-2"},
  ["cable-shielding-3"]={metal="silver",icon="cable-shield-3",tech="angels-components-cabling-3"},
  ["cable-shielding-4"]={metal="gold",icon="cable-shield-4",tech="angels-components-cabling-4"},
  ["cable-shielding-5"]={metal="platinum",icon="cable-shield-5",tech="angels-components-cabling-5"},
}
